### ISSUE TITLE
_curses.error: init_pair() returned ERR in iterm2

### ISSUE THREAD

**Issue by venatiodecorus** [mikedesu/asciishade#2]
```
➜  asciishade git:(main) echo $TERM
xterm-256color
➜  asciishade git:(main) python3 main.py
Traceback (most recent call last):
  File "/Users/venatio/dev/asciishade/main.py", line 160, in <module>
    wrapper(main)
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/Users/venatio/dev/asciishade/main.py", line 148, in main
    define_color_pairs()
  File "/Users/venatio/dev/asciishade/main.py", line 124, in define_color_pairs
    init_pair(x, i, j)
_curses.error: init_pair() returned ERR
```

**Comment by mikedesu** [comment]
I've tested this on my Macbook Pro mid-2012 running macOS 10.15.7 and using iTerm 3.0.15 with TERM="xterm-256color" and could not duplicate this error.

Are you on an M1 Max Macbook Pro like @AndroidKitKat ? 

I am going to need more information to try and duplicate this bug so that I can go about fixing it. I will be closing this issue until then since I am unable to duplicate this bug on my Macbook Pro in either Apple terminal or iTerm2. Best of luck. I hope it isn't an M1 issue :X

**Comment by venatiodecorus** [comment]
yes i'm running modern hardware. is this project only targeting older cpus? should probably add supported platforms to the README
